# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04c3ddbb0a45329700e41d188802a474d8552031f2c2410d558571a64a472bb581a89d873c0bdccc7c7a04d4e2440347eed64dc60358efac6ae7020cd0c127e2

test:
  secret_key_base: dade3b6a29c5b524f4bf61b0e40adac6c024935ed044e336556e80921a9f38b431c7505166abf240fa65e20a672865fdfe22d3dd51f0673d8ba68146fd898e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
